---
  - name: Deploying OVF template into vCenter
    vmware_deploy_ovf:
      hostname: 'rco1vcenter01.sbcuc.net'
      username: 'admin_labs@sbcuc.net'
      password: 'xxxxxxxxxx'
      datacenter: 'rco1datacenter'
      datastore: 'rco1r21106c01-local'
      folder: '/rco1datacenter'
      disk_provisioning: 'thin'
      name: 'asav-ovf-5'
      ovf: '/tmp/asav/asav-vi.ovf'
      ovf_networks:
        Management0-0: pg104-host-mgmt
        GigabitEthernet0-0: pg103-host-pxe
        GigabitEthernet0-1: pg103-host-pxe
        GigabitEthernet0-2: pg103-host-pxe
        GigabitEthernet0-3: pg103-host-pxe
        GigabitEthernet0-4: pg603-host-pxe
        GigabitEthernet0-5: pg603-host-pxe
        GigabitEthernet0-6: pg603-host-pxe
        GigabitEthernet0-7: pg603-host-pxe
        GigabitEthernet0-8: pg603-host-pxe
      deployment_option: 'ASAv10'
      property_map:
        'HARole': Standalone
#      customization:
#        domain: sbcuc.net
#        dns_servers:
#        - 10.224.0.209
#        - 10.224.130.69
      power_on: true
      wait: true
      wait_for_ip_address: false
      force: false
      validate_certs: False
    delegate_to: localhost
