- name: Update the python to 2714 and install pyvmomi along with anisble
  hosts: local
  user: root
  become: yes
  gather_facts: false
  vars_files:
    - ../vars/python2714.yml
  roles:
    - role: ../roles/python2714
