- name: Update the python to 2714 and install pyvmomi along with anisble
  hosts: local
  user: root
  become: yes
  gather_facts: false
# uncomment the below three lines if you have a proxy in your environment.
#  environment:
#    https_proxy: http://PROXY_SERVER:PORT/
#    http_proxy: http://PROXY_SERVER:PORT/

  vars_files:
    - ../vars/python2714.yml
  roles:
    - role: ../roles/python2714
