---
    - name: Ensure nfsutilities are installed
      #connection: local
      yum:
        name: nfs-utils
        state: present

    - name: Enable and Start the nfs-server and rpcbind
      #connection: local
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
         - "rpcbind"
         - "nfs-server"

    - name: Ensure export directories exist
      #connection: local
      file: 
        path: "{{ item.strip().split()[0] }}"
        state: directory
        owner: nfsnobody
        group: nfsnobody
        mode: 0776
      with_items: "{{ nfs_exports }}"
      notify: restart nfs

    - name: Copy exports file.
      #connection: local
      template:
        src: exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: 0644
      register: nfs_exports_copy
      notify: restart nfs

    - name: Restart NFS immediately if exports are updated.
      #connection: local
      service: 
        name: "nfs-server"
        state: restarted
      when: nfs_exports_copy.changed

    - name: Ensure nfs is running.
      #connection: local
      service:
        name: "nfs-server"
        state: started 
        enabled: yes
      when: nfs_exports|length
